grafik_eye:
  login: nwk
  ip: 192.168.178.14
  port: 23
  control_units:
    - name: Woonkamer
      id: 1
    - name: Keuken
      id: 2
    - name: Veranda
      id: 3
  scenes:
    - name: Uit
      id: 0
    - name: Scene 1
      id: 1
    - name: Scene 2
      id: 2
    - name: Scene 3
      id: 3
    - name: Scene 4
      id: 4